export const activities = [
  {
    id: 1,
    type: "Running",
    duration: "30 min",
    distance: "5 km",
    calories: 320,
    date: "Today, 8:30 AM",
    icon: "🏃‍♂️",
  },
  {
    id: 2,
    type: "Cycling",
    duration: "45 min",
    distance: "15 km",
    calories: 420,
    date: "Today, 5:30 PM",
    icon: "🚴‍♀️",
  },
  {
    id: 3,
    type: "Swimming",
    duration: "40 min",
    distance: "1 km",
    calories: 350,
    date: "Yesterday, 7:00 AM",
    icon: "🏊‍♂️",
  },
  {
    id: 4,
    type: "Yoga",
    duration: "60 min",
    distance: null,
    calories: 180,
    date: "Yesterday, 6:30 PM",
    icon: "🧘‍♀️",
  },
  {
    id: 5,
    type: "Weight Training",
    duration: "50 min",
    distance: null,
    calories: 280,
    date: "2 days ago, 4:00 PM",
    icon: "🏋️‍♂️",
  },
  {
    id: 6,
    type: "Walking",
    duration: "35 min",
    distance: "3 km",
    calories: 150,
    date: "3 days ago, 12:30 PM",
    icon: "🚶‍♀️",
  },
]